### PR TITLE
Message Requests Phase 1

### LINKED ISSUE #554: Open groups joined on desktop not showing up on iOS.
**Code of conduct**

- [x] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-ios/blob/master/CODE_OF_CONDUCT.md).

**Describe the bug**

Open groups joined on desktop not showing up on iOS.

**To reproduce**

Join a group on windows Session desktop client. It won't show up on iOS app.

**Screenshots or logs**

n/a

**Smartphone (please complete the following information):**

 - Device: iPhone XS
 - OS: iOS 15.2.1
 - Version of Session or latest commit hash: 1.11.20

**Additional context**

n/a

### PR DESCRIPTION
**Pull request by mpretty-cyro**
Fixes #554

Changes in this PR are:
- Added the Message Requests UI
- Added accept/reject buttons for message requests to the ConversationVC
- Added the ability to hide the message request item on the HomeVC (re-appears if you get a new message request)
- Added code to handle an edge-case where the message request approval state wouldn't be returned to the sender due to the recipient running an old version of the app
- Prevented contacts which aren't associated with an approved thread from appearing when creating a closed group
- Disabled notifications from message requests
- Updated the app notification count to exclude messages from message requests
- Updated the app to ignore closed group creation messages if the group has no admins which are approved contacts
- Fixed up the keyboard avoidance behaviour in the ConversationVC
- Fixed a couple of minor interaction issues which affected some devices
- Fixed an issue where the database migrations would run on the 2nd launch when creating a new account (causing odd behaviours)
- Fixed an issue where only the first config sync would get processed resulting in odd behaviours

### CODE REVIEW

File: Session/Conversations/ConversationVC.swift [hunk 1]
```diff
@@ -187,9 +296,50 @@ final class ConversationVC : BaseVC, ConversationViewModelDelegate, OWSConversat
...
+        
+        scrollButton.translatesAutoresizingMaskIntoConstraints = false
+        footerControlsStackView.addArrangedSubview(scrollButton)
+        footerControlsStackView.addArrangedSubview(messageRequestView)
+        
+        messageRequestView.addSubview(messageRequestDescriptionLabel)
+        messageRequestView.addSubview(messageRequestAcceptButton)
+        messageRequestView.addSubview(messageRequestDeleteButton)
+        
+        let footerControlsStackViewBottomConstraint: NSLayoutConstraint = footerControlsStackView.bottomAnchor.constraint(equalTo: view.bottomAnchor, constant: -16)
```
Comment (RyanRory) [inline Session/Conversations/ConversationVC.swift:314]: We have some encapsulated functions in `SessionUIKit` -> `UIView+Constraints` for layout. Could you use those functions instead?

File: Session/Home/HomeVC.swift [hunk 2]
```diff
@@ -203,28 +232,94 @@ final class HomeVC : BaseVC, UITableViewDataSource, UITableViewDelegate, NewConv
...
         tableView.beginUpdates()
-        rowChanges.forEach { rowChange in
+        
+        // If we need to unhide the message request row and then re-insert it
+        if !messageRequestInserts.isEmpty && UserDefaults.standard[.hasHiddenMessageRequests] {
+            UserDefaults.standard[.hasHiddenMessageRequests] = false
+            tableView.insertRows(at: [IndexPath(row: 0, section: 0)], with: .automatic)
+        }
+        
+        // TODO: Crash due to change from Message Requests getting approved?
```
Comment (RyanRory) [inline Session/Home/HomeVC.swift:292]: Left TODO here, has this issue been fixed?

**Review by RyanRory — CHANGES_REQUESTED** [review]
Just found some small issues, overall great job! I noticed the keyboard showing has been rebuilt, could you make sure this won't introduce any UI glitch? We fixed some corner cases a long time ago like #391 #372 #369 . Just want to make sure those issues won't come back.

File: Session/Conversations/ConversationVC.swift [hunk 3]
```diff
@@ -93,18 +95,29 @@ final class ConversationVC : BaseVC, ConversationViewModelDelegate, OWSConversat
...
         result.delegate = self
         return result
     }()
 
     lazy var messagesTableView: MessagesTableView = {
-        let result = MessagesTableView()
-        result.dataSource = self
-        result.delegate = self
-        return result
+        let tableView: MessagesTableView = MessagesTableView()
```
[the remark this answers is not in the document]
Comment (mpretty-cyro) [reply Session/Conversations/ConversationVC.swift:109]: Yea I can go through and change this throughout

File: Session/Conversations/ConversationVC.swift (hunk 1 above)
Comment (mpretty-cyro) [reply Session/Conversations/ConversationVC.swift:314]: I actually really don't like the `UIView+Constraints` extensions (and that there is a bunch of `PureLayout` mixed in elsewhere as well) - by using them we are basically inventing our own constraint management language which increases the learning curve for new people working on the project. And, with the exception of `pin(to:)` and `pin(to:withInset)` it doesn't really save much code (most things still take the same number of lines).

I'd also argue that by using `NSLayoutConstraint.activate()` you incentivise devs to keep all of their layout code together (since adding multiple `NSLayoutConstraint.activate` calls is a tiny inconvenience) whereas with the `pin()` functions seem to be in multiple places in a lot of the files they are used in (which makes it more likely to introduce bugs when modifying layouts since they are easy to miss).

If you take a look at `MessageRequestsViewController`, `MessageRequestsCell` or `MediaMessageView` you can see how the layout code is in a standardised location in each (the first two also have a nice separation between view configuration, view hierarchy setup and layout setup).

File: Session/Home/HomeVC.swift (hunk 2 above)
Comment (mpretty-cyro) [reply Session/Home/HomeVC.swift:292]: Ah yep this has been fixed (it's the `rowChange.originalGroup == TSMessageRequestGroup && rowChange.finalGroup == TSInboxGroup` logic) - I'll remove this todo

**Comment by mpretty-cyro** [comment]
> Just found some small issues, overall great job! I noticed the keyboard showing has been rebuilt, could you make sure this won't introduce any UI glitch? We fixed some corner cases a long time ago like #391 #372 #369 . Just want to make sure those issues won't come back.

Yep, just did some testing and the updated keyboard avoidance doesn't seem to run into any of those issues (it does behave a little odd when the link preview appears and disappears while typing but that's more due to how the link previews UI is designed rather than this logic - since it appears and disappears the messages list will scroll up and down with it's appearance and disappearance)

File: Session/Conversations/ConversationVC.swift (hunk 3 above)
[the remark this answers is not in the document]
Comment (mpretty-cyro) [reply Session/Conversations/ConversationVC.swift]: I've pushed up a fix for this

File: Session/Home/HomeVC.swift (hunk 2 above)
Comment (mpretty-cyro) [reply Session/Home/HomeVC.swift]: I've pushed up a fix for this

**Review by RyanRory — APPROVED** [review]

**Review by RyanRory — APPROVED** [review]

**Comment by RyanRory** [comment]
There's some conflicts on the translation files, could you resolve those and I'll merge this PR. :)

**Comment by mpretty-cyro** [comment]
> There's some conflicts on the translation files. Could you resolve those? And I'll merge this PR. :)

@RyanRory No worries, I've merged the latest dev in resolving the conflicts
