### PR TITLE
Bug fixes on 1.12.7

### LINKED ISSUE #447: Draft Edit Bug
When editing a message on iOS after you’ve already closed the app, it’s not easily editable if the message is longer than the displayed characters. To get around this you need to use the space bar to move the cursor to where you can’t see it and start typing to reinitiate focus below the displayed text above. Otherwise scrolling doesnt work.

To Reproduce, write a long message without sending. Then, long press a message thats been sent and deselect it. Now you won’t be able to edit the rest of your message unless you do the work around stated above.

iPhone 12 Pro
iOS 14.6
Session 1.11.6

### LINKED ISSUE #456: Selecting from gallery bug(s), can't unselect
When selecting an image or video, if you click back to your gallery you’re unable to deselect the original photo or video that was selected. Overall "glitchy"

iPhone 12 Pro
iOS 14.6
Session 1.11.6

### PR DESCRIPTION
**Pull request by RyanRory**
- Fix a background polling crash
- Fix #456 
- Fix #447 
- Fix rejected message requests coming back on linked devices
- Fix closed group issues
- Fix theme issues
- Fix title UI issues

### CODE REVIEW

File: Session/Shared/BaseVC.swift [hunk 1]
```diff
@@ -104,6 +105,10 @@ class BaseVC : UIViewController {
     deinit {
         NotificationCenter.default.removeObserver(self)
     }
+    
+    @objc func appDidBecomeActive(_ notification: Notification) {
+        // To be implemented
```
Comment (mpretty-cyro) [inline Session/Shared/BaseVC.swift:110]: This notification selector isn't doing anything - can we just revert the change?

**Review by mpretty-cyro — CHANGES_REQUESTED** [review]

File: Session/Shared/BaseVC.swift (hunk 1 above)
Comment (RyanRory) [reply Session/Shared/BaseVC.swift:110]: I noticed we have several view controllers adding the observer of `appDidBecomeActive` notification, just wanna to do that in `BaseVC` and clean up all the other ones. I'll make the code cleaner.

Comment (mpretty-cyro) [reply Session/Shared/BaseVC.swift:110]: Ah ok, no worries then

**Review by mpretty-cyro — APPROVED** [review]

**Review by mpretty-cyro — APPROVED** [review]
